FROM resin/%%RESIN_MACHINE_NAME%%-python:2-20161119

MAINTAINER Gergely Imreh <gergely@resin.io>

WORKDIR /usr/src/app/
ENV INITSYSTEM on

RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
      avahi-daemon avahi-utils libnss-mdns \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN systemctl enable avahi-daemon

COPY nsswitch.conf /etc/nsswitch.conf
COPY qotd.service /etc/avahi/services/
COPY app/* ./

CMD ["bash", "start.sh"]
